WebServer/Users/urls.py
from django.urls import path
from . import views

app_name = 'Users'
urlpatterns = [
    #ex /Users/
    path('',views.IndexView.as_view(), name='index'),
    #path('', views.index, name='index'),
    #ex /Users/Ryan/
    #path('<int:user_id>/', views.detail, name='detail'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    #ex /Users/Ryan/Widgets
    #path('<int:user_id>/Widgets/', views.widgets, name='widgets'),
    path('removeWidget/<int:pk>/', views.remWidget.as_view(), name='remwidget'),
    #ex /Users/Ryan/edit
    #path('<int:user_id>/edit/', views.pickWidgets, name='edit')
    path('<int:user_id>/edit/', views.pickWidgets, name='edit'),
    #ex /Users/add_user
    path('adduser/', views.addUser.as_view(success_url=""), name='adduser'),
    #ex /Users/add_widget
    path('updatewidgets/', views.addWidget.as_view(success_url=""), name='addwidget'),
    #ex /Users/Ryan/set/
    path('<int:user_id>/set/', views.SetCurrentUser, name='set'),
    #ex /Users/remove_user
    path('<int:pk>/remove_user/', views.remUser.as_view(), name='remuser'),
    #ex /Users/add_stock
    path('add_stock/', views.addStock.as_view(success_url=''), name='addstock'),
    #ex /Users/rem_stock
    path('rem_stock/<int:pk>/', views.remStock.as_view(success_url=''), name='remstock'),
]

WebServer/webserver/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic.base import TemplateView

urlpatterns = [
    path('Users/', include('Users.urls')),
    path("accounts/", include('django.contrib.auth.urls')),
    path("accounts/", include('accounts.urls')), 
    #path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name='home.html'), name='home'),

]

WebServer/Users/models.py
from django.db import models
from django.utils import timezone

# Create your models here.
def getWidgets():
    widgets= []
    with open("/home/ryan/Documents/webserver/Users/apps.txt", "r") as f:
        lines = f.readlines()
    for widget in lines:
        widgets.append((widget[:-3],widget))
    return widgets

available_widgets = getWidgets()

class User(models.Model):
    username=models.CharField(max_length=20)
    added_date = models.DateTimeField('Date Added', default = timezone.now)
    def __str__(self):
        return self.username
    def get_absolute_url(self):
        return u'/Users/'

available_stocks = []
with open("stocks.txt", "r") as f:
    available_stocks = f.readlines()

class Stock(models.Model):
    Ticker = models.CharField(max_length = 20, choices=[(str(i),available_stocks[i][:-1]) for i in range(len(available_stocks))])
    user = models.ForeignKey(User, on_delete=models.CASCADE, default = None)
    def __str__(self):
        return self.Ticker
    def get_absolute_url(self):
        return u'/Users/'

class Widget(models.Model):
    appname=models.CharField(max_length=20)
    user=models.ForeignKey(User,on_delete=models.CASCADE,default=None)
    added_date=models.DateTimeField('Date Added', default = timezone.now)
    creator=models.CharField(max_length=20, default = "Unknown")
    def __str__(self):
        return self.appname
    def get_absolute_url(self):
        return u'/Users/'

WebServer/polls/models.py
from django.db import models
import datetime
from django.utils import timezone

# Create your models here.
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    def __str__(self):
        return self.question_text
    def wasPublishedRecently(self):
        return self.pub_date >= timezone.now()


datetime.timedelta(days=1)

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self):
        return self.choice_text

WebServer/Users/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from django.template import loader
from .models import User, Widget, Stock
from django.urls import reverse, reverse_lazy
from django.views import generic
import json
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.admin.widgets import AdminDateWidget
# Create your views here.
@login_required
def index(request):
    Users = User.objects.order_by('-added_date')[:]
    template = loader.get_template('Users/index.html')
    context = {
        'Users': Users,
    }
    return HttpResponse(template.render(context, request))


class IndexView(LoginRequiredMixin,generic.ListView):
    template_name = 'Users/index.html'
    login_url = '/accounts/login/'
    redirect_field_name = 'redirect_to'
    context_object_name = 'latest_user_list'
    def get_queryset(self):
        users = User.objects.all()
        dict_of_users = {}
        for user in users:
            cur_dict = {}
            cur_dict['id'] = user.id
            appList = []
            for widget in user.widget_set.all():
                appList.append(widget.appname)
            cur_dict['apps'] = appList
            stockList= []
            for stock in user.stock_set.all():
                stockList.append(stock.get_Ticker_display())
            cur_dict['stocks'] = stockList
            dict_of_users[user.username] = cur_dict
        with open("users.json","w") as f:
            json.dump(dict_of_users, f)


        """Return the last five published questions."""
        return User.objects.order_by('-added_date')[::-1]

def SetCurrentUser(request, user_id):
    user = get_object_or_404(User, pk = user_id)
    with open("currentuser.txt", "w") as f:
        f.write(user.username)
    return render(request, 'Users/detail.html', {'User':user})

class DetailView(generic.DetailView):
    model = User
    template_name = 'Users/detail.html'

def detail(request, user_id):
    user = get_object_or_404(User, pk = user_id)
    return render(request, 'Users/detail.html', {'User': user})

def widgets(request, user_id):
    user = get_object_or_404(User, pk=user_id)
    return render(request, 'Users/widgets.html', {'user': user})

class WidgetView(generic.DetailView):
    model = Widget
    template_name = 'Users/widgets.html'

def pickWidgets(request, user_id):
    user = get_object_or_404(User, pk=user_id)
    try:
        selected_choice = user.widget_set.get(pk=request.POST['widget'])
    except (KeyError, Widget.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'Users/detail.html', {
            'User': user,
            'error_message': "You didn't select an app.",
        })
    else:
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        print(selected_choice)
        return HttpResponseRedirect(reverse('Users:results', args=(selected_choice.id,)))

class addUser(generic.edit.CreateView):
    model = User
    fields = ['username']
    def get_absolute_url(self):
        return reverse('')

class addWidget(generic.edit.CreateView, generic.ListView):
    model = Widget
    fields = ['appname', 'user', 'creator']
    def get_absolute_url(self):
        return reverse('Users:index')
    #context_object_name = 'pertinent'
    #def get_queryset(self):
    #    apps = []
    #    with open("apps.txt", "r") as f:
    #        apps = f.readlines()
        #print(apps)
        #return Widget.objects.order_by('-added_date', 'user')[::-1]
        #return(apps, User.objects.order_by('added_date')[::-1])

    def get_context_data(self, **kwargs):
        apps = []
        with open("apps.json", "r") as f:
            apps = json.load(f)
        context = super(addWidget, self).get_context_data(**kwargs)
        #context['latest_widget_list'] = Widget.objects.order_by('-added_date', 'user')[::-1]
        context['latest_widget_list'] = apps
        context['latest_user_list'] = User.objects.order_by('added_date')[::]

        return context

class addStock(generic.edit.CreateView):
    model = Stock
    fields = ['Ticker', 'user']
    def get_absolute_url(self):
        return reverse('User:index')
    def get_context_data(self, **kwargs):
        context = super(addStock, self).get_context_data(**kwargs)
        stocks = []
        with open("stocks.txt", "r") as f:
            stocks = f.readlines()
        context['latest_stock_list'] = stocks
        context['latest_user_list'] = User.objects.order_by('added_date')[::]
        return context

class remStock(generic.edit.DeleteView):
    model= Stock
    template_name = 'Users/delete_stock.html'
    def get_success_url(self):
        return reverse('Users:index')

class remWidget(generic.edit.DeleteView):
    model = Widget
    template_name = 'Users/delete_widget.html'
    def get_success_url(self):
        return reverse('Users:index')

class remUser(generic.edit.DeleteView): 
    model = User
    template_name = 'Users/delete_user.html'
    def get_success_url(self):
        return reverse('Users:index')

WebServer/Users/templates/Users/addWidget.html
{% if latest_app_list  %}
        <ul>
        {% for app in latest_app_list %}
	<li>{{app.appname}}</li>
        {% endfor %}
        </ul>
{% else %}
        <p>No Widgets have been created yet</p>
{% endif %}

<ul>
	<li><a href = "{% url 'Users:index" %}>Return To Users</a></li>
</ul>

WebServer/Users/templates/Users/delete_stock.html
{% extends "base.html" %}

{% block content %}

<h1>Remove Stock?</h1>
<p>
 	Stock Ticker: &nbsp;&nbsp;&nbsp; {{stock.get_Ticker_display}}
</p>

<p>Are you sure you want to delete this app assignment {{ stock.get_Ticker_display }}?</p>

<form action="{% url "Users:remstock" pk=stock.id %}" method="POST">
  {% csrf_token %}

  <input type="submit" value="Yes, delete." />
  <a href="{% url 'Users:index'%}">No, cancel.</a>
</form>

{% endblock %}

WebServer/Users/templates/Users/delete_user.html
{% extends "base.html" %}

{% block content %}

<h1>Delete User</h1>

<p>Are you sure you want to delete the user {{ user }}?</p>

<form action="{% url "Users:remuser" pk=user.id %}" method="POST">
  {% csrf_token %}

  <input type="submit" value="Yes, delete." />
  <a href="{% url "Users:index" %}">No, cancel.</a>
</form>

{% endblock %}

WebServer/Users/templates/Users/delete_widget.html
{% extends "base.html" %}

{% block content %}

<h1>Remove Widget?</h1>
<h3>Widget Details</h3>
<p>
 	App Name: &nbsp;&nbsp;&nbsp; {{widget.appname}}
	<br>App Creator:&nbsp; {{widget.creator}}
	<br>Current User: {{widget.user}}
</p>

<p>Are you sure you want to delete this app assignment {{ widget }}?</p>

<form action="{% url "Users:remwidget" pk=widget.id %}" method="POST">
  {% csrf_token %}

  <input type="submit" value="Yes, delete." />
  <a href="{% url 'Users:index'%}">No, cancel.</a>
</form>

{% endblock %}

WebServer/Users/templates/Users/detail.html
<h1> {{user.username}} </h1>
{% if error_message %}<p><strong>{{error_message}}</strong></p>{% endif %}
<h3>Configured Widgets</h3>
{% if user.widget_set.all %}
	{% for app in user.widget_set.all %}
		<ul>
		<li><a href="{% url 'Users:remwidget' app.id%}">{{app.appname}}</a></li>
	</ul>

{% endfor %}
{% else %}
	No apps configured for this user
{% endif %}
<h3>Preferred Stocks (Only top 4 will be displayed)</h3>
{% if user.stock_set.all %}
{% for app in user.stock_set.all %}
		<ul>
		<li><a href="{% url 'Users:remstock' app.id%}">{{app.get_Ticker_display}}</a></li>
	</ul>

{% endfor %}
{% else %}
	No stocks configured for this user
{% endif %}
<h3>
	Remove this user?
</h3>
{% if user.id %}
<ul>
	<a href="{% url 'Users:remuser' user.id %}">Delete</a>
</ul>
{% endif %}

<br><br><a href="{% url 'Users:index' %}">Return</a>

WebServer/Users/templates/Users/index.html
<h1>Current Users</h1>
{% if latest_user_list  %}
	<ul>
	{% for user in latest_user_list %}
	<li><a href = "{% url 'Users:detail' user.id %}">{{user.username}}</a></li>
	{% endfor %}
	</ul>
{% else %}
	<p>No users created yet</p>
{% endif %}
<h1>Management</h1>
<ul>
	<li><a href = "{% url 'Users:adduser' %}">Add User</a></li>
</ul>

<ul>
	<li><a href = "{% url 'Users:addwidget' %}">Add Widget</a></li>
</ul>
<ul>
	<li><a href = "{% url 'Users:addstock' %}">Add Stock Preferences</a></li>
</ul>

WebServer/Users/templates/Users/stock_form.html
<h1>Available Stocks</h1>
{% if latest_stock_list %}
	<ul>
	{% for stock in latest_stock_list %}
	<!--	<li><a>{{widget.appname}}, {{widget.user.username}}</a></li> --!>
	 <li><a>{{stock}}</a></li>
	{% endfor %}
	</ul>
	<h1>Available Users</h1>
	{% if latest_user_list %}
		<ul>
		{% for user in latest_user_list %}
		<li><a>{{user.username}}</a></li>
		{% endfor %}
		</ul>
		<form method="post">
		{% csrf_token %}
	    	{{ form.as_p }}
	    	<input type="submit" value="Add Stock">
		</form>

	{% else %}
		<p>No Users Have Been Created Yet</p>
		<ul>
		<li><a href = "{% url 'Users:adduser' %}">Add User</a></li>
		</ul>

{% endif %}
{% else %}
<p>No Widgets Have Been Added Yet</p>
{% endif %}

<a href="{% url 'Users:index' %}">Return</a>

WebServer/Users/templates/Users/user_confirm_delete.html
<form method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input type="submit" value="Confirm">
</form>

WebServer/Users/templates/Users/user_form.html
<form method="post">
{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Add User">
</form>

WebServer/Users/templates/Users/widget_form.html
<h1>Available Widgets</h1>
{% if latest_widget_list %}
	<ul>
	{% for widget, details in latest_widget_list.items %}
	<!--	<li><a>{{widget.appname}}, {{widget.user.username}}</a></li> --!>
	 <li><a>{{widget}} - {{details.creator}} </a>
		<br>&nbsp;&nbsp;&nbsp;{{details.description}}
		</li>
	{% endfor %}
	</ul>
	<h1>Available Users</h1>
	{% if latest_user_list %}
		<ul>
		{% for user in latest_user_list %}
		<li><a>{{user.username}}</a></li>
		{% endfor %}
		</ul>
		<form method="post">
		{% csrf_token %}
	    	{{ form.as_p }}
	    	<input type="submit" value="Add Widget">
		</form>

	{% else %}
		<p>No Users Have Been Created Yet</p>
		<ul>
		<li><a href = "{% url 'Users:adduser' %}">Add User</a></li>
		</ul>

{% endif %}
{% else %}
<p>No Widgets Have Been Added Yet</p>
{% endif %}

<a href="{% url 'Users:index' %}">Return</a>

WebServer/Users/templates/Users/widgets.html
<h1>{{ user.username }}</h1>

<ul>
{% for choice in user.choice_set.all %}
    <li>{{ choice.appname }} -- {{ choice.user }} pickWidgets{{ choice.user|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'Users:detail' user.id %}">Pick New Widgets?</a>