WebServer/Users/urls.py
from django.urls import path
from . import views

app_name = 'Users'
urlpatterns = [
    #ex /Users/
    path('',views.IndexView.as_view(), name='index'),
    #path('', views.index, name='index'),
    #ex /Users/Ryan/
    #path('<int:user_id>/', views.detail, name='detail'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    #ex /Users/Ryan/Widgets
    #path('<int:user_id>/Widgets/', views.widgets, name='widgets'),
    path('removeWidget/<int:pk>/', views.remWidget.as_view(), name='remwidget'),
    #ex /Users/Ryan/edit
    #path('<int:user_id>/edit/', views.pickWidgets, name='edit')
    path('<int:user_id>/edit/', views.pickWidgets, name='edit'),
    #ex /Users/add_user
    path('adduser/', views.addUser.as_view(success_url=""), name='adduser'),
    #ex /Users/add_widget
    path('updatewidgets/', views.addWidget.as_view(success_url=""), name='addwidget'),
    #ex /Users/Ryan/set/
    path('<int:user_id>/set/', views.SetCurrentUser, name='set'),
    #ex /Users/remove_user
    path('<int:pk>/remove_user/', views.remUser.as_view(), name='remuser'),
    #ex /Users/add_stock
    path('add_stock/', views.addStock.as_view(success_url=''), name='addstock'),
    #ex /Users/rem_stock
    path('rem_stock/<int:pk>/', views.remStock.as_view(success_url=''), name='remstock'),
]

WebServer/accounts/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup'),
]

WebServer/webserver/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic.base import TemplateView

urlpatterns = [
    path('Users/', include('Users.urls')),
    path("accounts/", include('django.contrib.auth.urls')),
    path("accounts/", include('accounts.urls')), 
    #path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name='home.html'), name='home'),

]

WebServer/accounts/models.py
from django.db import models

# Create your models here.

WebServer/accounts/views.py
from django.shortcuts import render
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views import generic


class SignUp(generic.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'signup.html'
# Create your views here.

WebServer/accounts/templates/base.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>{% block title %}Django Auth Tutorial{% endblock %}</title>
</head>
<body>
  <main>
    {% block content %}
    {% endblock %}
  </main>
</body>
</html>

WebServer/accounts/templates/home.html
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
<h1>Welcome to the IOT inc Smart Mirror</h1>
{% if user.is_authenticated %}
  Hi {{ user.username }}!
  <p><a href="{% url 'Users:index' %}">Manage Users</a></p> 
  <p><a href="{% url 'logout' %}">logout</a></p>
{% else %}
  <p>You are not logged in :( </p>
  <a href="{% url 'login' %}">login</a>

  <p><a href="{% url 'signup' %}">New User? Create an Account Here</a></p>
{% endif %}
{% endblock %}

WebServer/accounts/templates/signup.html
{% extends 'base.html' %}

{% block title %}Sign Up{% endblock %}

{% block content %}
  <h2>Sign up</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Sign up</button>
  </form>
{% endblock %}